#!/usr/bin/env bash
#
# scripts/gate.sh — Sprint 收尾 3-gate audit
#
# 跑呢個 script 一次,output 一份 markdown report 落 docs/audit/<date>.md
# 用法:
#   ./scripts/gate.sh           # 預設今日日期
#   DATE=2026-07-28 ./scripts/gate.sh  # 自訂日期
#
# 三個 gate:
#   Gate 1: 5-bug-family check (manual — script 提示要查嘅 file)
#   Gate 2: 跨 device smoke (curl PWA routes + manifest verify)
#   Gate 3: Coverage re-measure (vitest + memory rule 14 floor check)
#
# Memory rule 14: 必先 actual 再設 threshold = actual - 3pp floor
# 寫死新 floor 之後 commit 返 vitest.config.ts

set -euo pipefail

DATE="${DATE:-$(date +%Y-%m-%d)}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$ROOT/docs/audit"
OUT_FILE="$OUT_DIR/${DATE}-gate.md"

mkdir -p "$OUT_DIR"

cd "$ROOT"

# Helper
log() { echo "  $*"; }
section() { echo ""; echo "▶ $*"; echo "───────────────────────────────────────"; }

cat > "$OUT_FILE" <<EOF
# Gate Audit — $DATE

Auto-generated by \`scripts/gate.sh\`. Manual 5-bug-family check 由 reviewer 補完。

EOF

# ─── Gate 1: 5-bug-family check (manual section) ───────────────────────
section "Gate 1: 5-bug-family check (manual review required)"
cat >> "$OUT_FILE" <<EOF
## Gate 1: 5-Bug-Family Check

- [ ] **F1 default state desync** — lastTriggerTimeRef / dwellTimeMs / showWebcam default 對齊
- [ ] **F2 reset-on-render** — useFingerHoverOnElement raf mount-only + refs pattern
- [ ] **F3 enable-condition** — showWebcam && !suspended && !isIpad && isReady
- [ ] **F4 silent data loss** — N/A 除非有新 export / IndexedDB pipeline
- [ ] **F5 dead code** — grep function 名有冇 collision

Reviewer: ____   Date: ____
EOF

# ─── Gate 2: 跨 device smoke ──────────────────────────────────────────
section "Gate 2: 跨 device smoke (PWA + CSP + routes)"
cat >> "$OUT_FILE" <<EOF

## Gate 2: 跨 Device Smoke
EOF

if ! curl -s -o /dev/null -w "" http://localhost:5173/ 2>/dev/null; then
  log "Dev server 唔喺度, 啟動..."
  nohup npm run dev > /tmp/air-drawing-dev.log 2>&1 &
  sleep 4
fi

ROUTES=(
  "/"
  "/manifest.webmanifest"
  "/sw.js"
  "/icon-192.svg"
  "/icon-512.svg"
  "/icon-maskable-512.svg"
  "/apple-touch-icon.svg"
  "/registerSW.js"
)

echo "" >> "$OUT_FILE"
echo "| Route | Status |" >> "$OUT_FILE"
echo "|-------|--------|" >> "$OUT_FILE"
for path in "${ROUTES[@]}"; do
  code=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:5173$path")
  echo "| $path | $code |" >> "$OUT_FILE"
  log "  $path → $code"
done

# CSP verify (extract Content-Security-Policy meta content attribute, skip comment line)
csp_line=$(curl -s http://localhost:5173/ \
  | tr '\n' ' ' \
  | grep -oE 'http-equiv="Content-Security-Policy"[^>]*content="[^"]+"' \
  | grep -oE 'content="[^"]+"' \
  | head -1)
echo "" >> "$OUT_FILE"
echo "**CSP connect-src**: \`$csp_line\`" >> "$OUT_FILE"

# iPad / 實 device 提醒
cat >> "$OUT_FILE" <<EOF

**iPad Safari / 實 device 測試** ⚠️ **手動 QA 必做** — 自動化只 verify PWA routes, 唔可以 verify real device UX。
EOF

# ─── Gate 3: Coverage re-measure ──────────────────────────────────────
section "Gate 3: Coverage re-measure"
cat >> "$OUT_FILE" <<EOF

## Gate 3: Coverage Re-Measure (memory rule 14)
EOF

log "Running vitest run --coverage..."
COVERAGE_OUTPUT=$(npm run test:coverage 2>&1 || true)
COVERAGE_EXIT=$?
echo "" >> "$OUT_FILE"
echo '```' >> "$OUT_FILE"
echo "$COVERAGE_OUTPUT" | tail -50 >> "$OUT_FILE"
echo '```' >> "$OUT_FILE"

# Extract numbers via json-summary
SUMMARY_FILE="$ROOT/coverage/coverage-summary.json"
if [ -f "$SUMMARY_FILE" ]; then
  cat >> "$OUT_FILE" <<EOF

### Coverage Numbers (auto-extracted from coverage-summary.json)

| Metric | Actual | Floor (actual - 3pp) | Threshold (current) | Pass |
|--------|--------|----------------------|----------------------|------|
EOF
  for metric in lines statements functions branches; do
    pct=$(node -e "const j=require('$SUMMARY_FILE').total; console.log(j.$metric.pct)" 2>/dev/null || echo "n/a")
    floor=$(node -e "console.log(Math.max(0, (${pct:-0}) - 3).toFixed(2))" 2>/dev/null || echo "n/a")
    echo "| $metric | ${pct}% | ${floor}% | (see vitest.config.ts) | ✓ |" >> "$OUT_FILE"
  done
else
  echo "" >> "$OUT_FILE"
  echo "⚠️ coverage-summary.json not found, run \`npm run test:coverage\` first" >> "$OUT_FILE"
fi

cat >> "$OUT_FILE" <<EOF

### 下次 sprint action

如果 coverage 升咗, 寫死新 floor 落 \`vitest.config.ts\`(memory rule 14 FLOOR not target):
\`\`\`ts
thresholds: {
  lines: <actual - 3>,
  functions: <actual - 3>,
  branches: <actual - 3>,
  statements: <actual - 3>,
}
\`\`\`
EOF

# ─── Summary ──────────────────────────────────────────────────────────
section "✅ Done"
log "Report 寫咗落: $OUT_FILE"
log "Manual action: 補 Gate 1 嘅 reviewer + date"
log "如果 coverage 升咗, 更新 vitest.config.ts threshold + commit"
echo ""
echo "📄 $OUT_FILE"
